# Generated by Django 4.2.7 on 2025-05-22 14:10

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userprofile_receive_event_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=pyuploadcare.dj.models.ImageField(blank=True, null=True),
        ),
    ]
