# Generated by Django 4.2.7 on 2025-05-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image_alter_userprofile_profile_picture'),
    ]

    operations = [
    ]
